### ISSUE TITLE
Failed generation specifying the file

### ISSUE THREAD

**Issue by l-vitaly** [swipe-io/swipe#9]
**Describe the bug**
Failed generation 

**To Reproduce**
1. Run generation specifying the file: `swipe gen -v ./pkg/transport/transport.go`
2. See error

```
Swipe v2.0.0-alpha.9
Thanks for using swipe
Please wait the command is running, it may take some time
panic: runtime error: index out of range [2] with length 1

goroutine 1535 [running]:
github.com/swipe-io/swipe/v2/internal/interface/gateway.(*serviceGateway).load(0xc004caa2c0, 0xc000111810, 0x127d561, 0xc000298fc0)
    /Users/sah4ez/go/src/github.com/swipe-io/swipe/internal/interface/gateway/service.go:353 +0xac5
github.com/swipe-io/swipe/v2/internal/interface/gateway.NewServiceGateway(0xc000149e60, 0xc000111810, 0xc0000b5380, 0xc0000b5360, 0x3, 0xc00025df90, 0xc00045b4e0, 0x5)
    /Users/sah4ez/go/src/github.com/swipe-io/swipe/internal/interface/gateway/service.go:718 +0xee
github.com/swipe-io/swipe/v2/internal/interface/registry.(*registryProcessor).NewProcessor(0xc00009f1c0, 0xc0023eae00, 0xc0000d3720, 0xc0082c2ae0, 0x0, 0x0, 0x0)
    /Users/sah4ez/go/src/github.com/swipe-io/swipe/internal/interface/registry/processor.go:31 +0x2bb
github.com/swipe-io/swipe/v2/internal/interface/executor.(*generationExecutor).processOptions.func1.1(0xc00e3798e0, 0xc00008ca00, 0xc0000d3720, 0xc00db3c720, 0xc00db3c6c0, 0xc0023eae00)
    /Users/sah4ez/go/src/github.com/swipe-io/swipe/internal/interface/executor/generation.go:48 +0xa9
created by github.com/swipe-io/swipe/v2/internal/interface/executor.(*generationExecutor).processOptions.func1
    /Users/sah4ez/go/src/github.com/swipe-io/swipe/internal/interface/executor/generation.go:46 +0xc7
```

**Expected behavior**
No errors

**Swipe Version:**
v2.0.0-alpha.9

**Comment by l-vitaly** [comment]
fixed
